version: '3.7'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: timeser_mongo
        restart: "unless-stopped"
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=turbit!
        image: mongo
        volumes:
            - "/home/leonardo/Desktop/programs/turbit/timeseries/database:/data/db"
            - "/home/leonardo/Desktop/programs/turbit/timeseries/api:/var/fakeapi"

